### ISSUE TITLE
1.16.5 server crash

### ISSUE THREAD

**Issue by Daejangnamu** [Kqy9/Wyrmroost#296]
**Description of issue:**
[crash-2021-07-10_15.34.03-server.txt](https://github.com/Kqy9/Wyrmroost/files/6795203/crash-2021-07-10_15.34.03-server.txt)

forge-1.16.5-36.1.32

**Comment by Therzis** [comment]
Could you provide a description of the issue instead of just the crash log?

**Comment by Daejangnamu** [comment]
> Could you provide a description of the issue instead of just the crash log?

If an error occurs again, I will report it.
I don't know the exact cause either.

**Comment by ternsip** [comment]
> Could you provide a description of the issue instead of just the crash log?

Actually it's quite visible that dragon fires breathing projectiles and it crashes
```
at com.github.wolfshotz.wyrmroost.entities.projectile.DragonProjectileEntity.func_70071_h_(DragonProjectileEntity.java:63) ~[wyrmroost:1.16.3-1.2.11] {re:classloading}
	at com.github.wolfshotz.wyrmroost.entities.projectile.breath.FireBreathEntity.func_70071_h_(FireBreathEntity.java:37) ~[wyrmroost:1.16.3-1.2.11] {re:classloading}
	```
